-- Phase 2 inventory: per-shop stock locations, stock levels (available/reserved per variant per
-- location), and reservations (holds taken during checkout). These are TENANT tables — sharded and
-- indexed by shop_id. Inventory references a catalog variant only by id (variant_id); there is no
-- cross-module FK to the catalog tables — the two contexts integrate via events. Versioned V5 so it
-- never collides with the other per-shard tenant migrations (platform V1, hello V2, identity V3,
-- catalog V4) when they share one physical database in dev/test; control is V100+.

CREATE TABLE stock_location (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    shop_id    BIGINT       NOT NULL,
    name       TEXT         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_stock_location PRIMARY KEY (shop_id, id)
);
CREATE INDEX idx_stock_location_shop ON stock_location (shop_id);

CREATE TABLE stock_level (
    shop_id     BIGINT       NOT NULL,
    variant_id  BIGINT       NOT NULL,   -- catalog variant id (opaque to inventory)
    location_id BIGINT       NOT NULL,
    available   BIGINT       NOT NULL,
    reserved    BIGINT       NOT NULL DEFAULT 0,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_stock_level PRIMARY KEY (shop_id, variant_id, location_id),
    -- Same-shard composite FK to the location (shop_id is part of both keys).
    CONSTRAINT fk_stock_level_location FOREIGN KEY (shop_id, location_id)
        REFERENCES stock_location (shop_id, id),
    CONSTRAINT ck_stock_level_nonneg CHECK (available >= 0 AND reserved >= 0)
);
CREATE INDEX idx_stock_level_shop ON stock_level (shop_id);

CREATE TABLE stock_reservation (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    shop_id     BIGINT       NOT NULL,
    variant_id  BIGINT       NOT NULL,
    location_id BIGINT       NOT NULL,
    quantity    BIGINT       NOT NULL,
    status      VARCHAR(16)  NOT NULL,   -- ReservationStatus: HELD | RELEASED | COMMITTED | EXPIRED
    expires_at  TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_stock_reservation PRIMARY KEY (shop_id, id),
    CONSTRAINT ck_stock_reservation_qty CHECK (quantity > 0)
);
CREATE INDEX idx_stock_reservation_shop ON stock_reservation (shop_id);
-- The expiry sweep scans held reservations past their deadline.
CREATE INDEX idx_stock_reservation_due ON stock_reservation (shop_id, status, expires_at);
