-- Phase 2 catalog: per-shop products and their variants (the priced, purchasable units).
-- These are TENANT tables — sharded and indexed by shop_id. Catalog owns merchandising data only; stock
-- lives in the inventory module and is integrated via events, never a shared table or cross-module FK.
-- Versioned V4 so it never collides with the other per-shard tenant migrations (platform V1, hello V2,
-- identity V3) when they share one physical database in dev/test; control is V100+.

CREATE TABLE product (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    shop_id      BIGINT       NOT NULL,
    title        TEXT         NOT NULL,
    description  TEXT,
    handle       TEXT         NOT NULL,   -- URL slug, unique per shop
    status       VARCHAR(16)  NOT NULL,   -- ProductStatus name: DRAFT | ACTIVE | ARCHIVED
    vendor       TEXT,
    product_type TEXT,
    published_at TIMESTAMPTZ,             -- null until first published; cleared on unpublish
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    -- shop_id is part of the key: a shard holds many shops, so the tenant key scopes every row.
    CONSTRAINT pk_product PRIMARY KEY (shop_id, id),
    CONSTRAINT uq_product_handle UNIQUE (shop_id, handle)
);
-- Every tenant table is indexed by shop_id.
CREATE INDEX idx_product_shop ON product (shop_id);

CREATE TABLE product_variant (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    shop_id        BIGINT        NOT NULL,
    product_id     BIGINT        NOT NULL,
    sku            TEXT,
    title          TEXT          NOT NULL,
    price_amount   NUMERIC(19,4) NOT NULL,
    price_currency CHAR(3)       NOT NULL,   -- ISO 4217
    position       INTEGER       NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    CONSTRAINT pk_product_variant PRIMARY KEY (shop_id, id),
    -- Same-shard composite FK (shop_id is part of the key) — never a cross-shard reference.
    CONSTRAINT fk_product_variant_product FOREIGN KEY (shop_id, product_id)
        REFERENCES product (shop_id, id) ON DELETE CASCADE
);
CREATE INDEX idx_product_variant_shop ON product_variant (shop_id);
CREATE INDEX idx_product_variant_product ON product_variant (shop_id, product_id);
